# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Lanyon
tagline:          'R. Stephen Hill'
description:      test
url:              http://lanyon.getpoole.com

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

excerpt_separator: ""

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/poole/lanyon

